# Make a user key
# mkdir -p ~/.config/sops/age
# age-keygen -o ~/.config/sops/age/keys.txt
# chmod 600 ~/.config/sops/age/keys.txt

# Display the user public key:
# age-keygen -y ~/.config/sops/age/keys.txt

# Make a host public key:
# nix-shell -p ssh-to-age
# ssh-to-age -i /etc/ssh/ssh_host_ed25519_key.pub

# Add secrets
# sops secrets/secrets.yaml

# Rekey secrets.yaml after editing recipients in .sops.yaml:
# sops updatekeys secrets/secrets.yaml
keys:
  - &users:
    - &alexander 07E36E87C0270E464DB4D663B423D1630A58837C
    
  - &hosts:
    - &desktop age1kjlpt0mu072vqk8txgkfs7yvehkvk0kysawyqvy96zcqmf49wgkq3hlsag

    
creation_rules:
   
  - path_regex: modules/nixos/secrets.ya?ml$
    key_groups:
    - gpg:
      - *alexander
      age:
      - *desktop
      

#  - path_regex: modules/nixos/services/secrets.ya?ml$
#    key_groups:
#    - gpg:
#      - *alexander

  - path_regex: modules/home/secrets.ya?ml$
    key_groups:
    - gpg:
      - *alexander
      age:
      - *desktop
     
