# Make a user key
# mkdir -p ~/.config/sops/age
# age-keygen -o ~/.config/sops/age/keys.txt
# chmod 600 ~/.config/sops/age/keys.txt

# Display the user public key:
# age-keygen -y ~/.config/sops/age/keys.txt

# Make a host public key:
# nix-shell -p ssh-to-age
# ssh-to-age -i /etc/ssh/ssh_host_ed25519_key.pub

# Add secrets
# sops secrets/secrets.yaml

# Rekey secrets.yaml after editing recipients in .sops.yaml:
# sops updatekeys secrets/secrets.yaml
keys:
  - &users:
    - &alexander 07E36E87C0270E464DB4D663B423D1630A58837C

  - &hosts:
    - &desktop age1kjlpt0mu072vqk8txgkfs7yvehkvk0kysawyqvy96zcqmf49wgkq3hlsag
    - &server age1qap92qp262npfhtqwwccu7jaxmjfyc22aeqwu5fv2kft828eaypqjzxx86
    - &workbook age123w5drucfk50cvw26lt6mrhhnmrdjshg7waqsp4ufnm69ujc04gqhu4h3r
    - &homebook age1wp0s79lec46vutqseazpm8m23uvn2qlpa49p8kpefuvt0v7agqwqeh3n3u
    - &vm age1wfx3942t957wq5e62wp5t7zf6qm2mwunusz62q4rgs0x62mr3sgqr20gp9
    - &tempbook age1u3qpszcmje9rf3qm4yt3h5qft3me79auk8k9eua0vjcvdkvm95csgazfmr

creation_rules:
  - path_regex: modules/nixos/secrets.ya?ml$
    key_groups:
      - pgp:
          - *alexander
        age:
          - *desktop
          - *server
          - *homebook
          - *vm

  - path_regex: modules/home/secrets.ya?ml$
    key_groups:
      - pgp:
          - *alexander
        age:
          - *desktop
          - *workbook
          - *homebook
          - *vm

  - path_regex: modules/darwin/secrets.ya?ml$
    key_groups:
      - pgp:
          - *alexander
        age:
          - *workbook
          - *tempbook

  - path_regex: infra/router/secrets.ya?ml$
    key_groups:
      - pgp:
          - *alexander
        age:
          - *desktop
          - *workbook
