state-passphrase: ENC[AES256_GCM,data:pXaeTAciIYpc/GkL4aicBdznmjHopJidDDuxqZXX7D8+wMrNrHKQe8VRQoQ=,iv:M/GPsCYQ9b32QI4HFvTy7fPG4vV5Tt5YEIi38uh8xXA=,tag:CG8CmRygRzrrGCxWroI5GA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBub25JaWdsdm52Qjk3SW9D
            bm0xVmlqTWttNndRL0ZnZ1k1cDlyOUgyYlZnCnBFYWd3L2syY01LZFUyMzdOVUVC
            dkFxV1MyZGNZT1JSOTZKTkxDZUJ4L2cKLS0tIGFRTW1PZVpnQ1RQSzFvdTQzbVFP
            QmlWMGpkNHRzZ1RYbDUyZWNXZ2ovMVkKbCcdJlRdL/iR1Cy6cILh7iy9akJAREuI
            F4Giq2IZjq52A+OfdBilzYQVsgKSzV6omqPO1Unzx0BZpqd7Z8unYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age123w5drucfk50cvw26lt6mrhhnmrdjshg7waqsp4ufnm69ujc04gqhu4h3r
    lastmodified: "2026-10-08T11:44:59Z"
    mac: ENC[AES256_GCM,data:0STLGAQd+49tWEmhAkYvRO+fUi2gdPME9pXEN/b/PfXCxRT2N2pPq+sPi0b+zjAfmkI1kfleygsqa04c7NZNwcQXP0jwGzKutsS9n+Gkr3H1PkZ+X8EABqWbBBW77n3WvG0k1k/VT1ya5C1bmrHRXsLa1THwS43w+SclkWKYliw=,iv:zxgxjyS4rXK+d6Ith4SlzlIP02Yk/uFlMJREzmwDz6M=,tag:iFi6yKqDeH+A9KDzBu8d5w==,type:str]
    pgp:
        - created_at: "2026-10-08T11:15:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DtCPRYwpYg3wSAQdAuJ9niSmkWnap20uoepx/A4uNJU8BL0ntrYE+QUJ2+yow
            s0piAhQolAeFeBTc16CJOlURtdkJUiWWeG4k2jOMGoKP0L2CqowaAbRRdee7EUtB
            0l4BTpVoLAjsdU1Lb5lX6rI5pyVDDDHaLI/pL55XRZv44A4x+yTnEg/hKLtI2Sff
            yq2qNA4noEjG+Yuxc0LgU1Qso7NcfK3Ej396jbcCdDUZWalDoZ+q6LfrxKiE4ues
            =1HtK
            -----END PGP MESSAGE-----
          fp: 07E36E87C0270E464DB4D663B423D1630A58837C
    unencrypted_suffix: _unencrypted
    version: 3.13.3
