cloudflare-api-token: ENC[AES256_GCM,data:IkvWX40t2l2yam3euV9nZ2r2pFq6h+IxfWsv+byA/Mc3zMJRUjBN6mYU1c7DUZ66DRVqnPs=,iv:WTWqQI0sVSoEK9O8z+Aq/Sg82HxgGeDyP5SazXLtaAc=,tag:49Nn11GYsk7Ch/v89+xW8w==,type:str]
tailscale-oauth-client-id: ENC[AES256_GCM,data:8yGBuOAKgbvsvwRWV5be7Do=,iv:h/8GyWtCbCajZx1Gyic7pqM4lMVJJnToRoszjT3uOLY=,tag:ZOsyS08+HOn0Xtco10ef0g==,type:str]
tailscale-oauth-client-secret: ENC[AES256_GCM,data:perQ4WqpFwlSNSpAZgaG5vu+VgmLqsDhfxhOueDqcbW5QdQ4v9/3JE2zLynbQnr3BHfCmDgAKay6VErPYMQA2g==,iv:3OjZ0iq49cKhshraNFgrbo1gPSxg2DX1ADun1nSH+lo=,tag:UP19GdOk1q9/rcMDQHpy2w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcGNyTHozV0w2NXR5dFBF
            b0JNNTZ4Z0IwS0huUWpqVDcrYStYVU1HaEc0ClRWM1lrWEdEWkN3N3c0eXo4aXRs
            WHovYTJyaUwySno1NlR6TEFHbE1LT3cKLS0tIHY3V1JqYkVCQUNhLzJqc21QeEU4
            UUtwc2ZiWGJ4bDFLS3FqOFNCa0tqSjAKpwKTvIuz4YNnCijdg4GUb8EWHpcEkAxC
            xSs/s8IXb6O1fAqZo7gfVupzbrzdvZsGf3+oTm0C+Emkr+kwWt2tpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age123w5drucfk50cvw26lt6mrhhnmrdjshg7waqsp4ufnm69ujc04gqhu4h3r
    lastmodified: "2026-10-08T11:44:52Z"
    mac: ENC[AES256_GCM,data:NcyOgrqfLoyo+GQe7PEm6bYDir5WnDhdJy4cbwVJBvIiZVLGnzukppnU5gebiTRbbVUauHH9T/XvUScog2MLwgibv7ZcNvN4i/LuBpuDiWfo/rIM5cvCL0cwt0lXYBy+5Nw9VwUIx43OOIvsaljzL2LWkwRZlcFIz7alHwHj2Iw=,iv:d44+7S2NJpp8ySuQHbKffla2SibevsT9Io/qZTNgoaI=,tag:WXGaGR5jTwKIHMObE3KfRQ==,type:str]
    pgp:
        - created_at: "2026-10-08T11:44:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DtCPRYwpYg3wSAQdAZ3hOniIfkOVqh00zgMTm6bMsupXWNxl1oSljwK7SCG8w
            w7+RrXFluWDA5cPs/zcw2PcNsp6jsn3V3u4GqVOK+gEJHVEyT/Xe83vrcKmY/BBA
            0lwBePGXtYwZcV13kWfYhwit/uEqYop6CnoebinCU7kRgxnb/8lx7hUXSV59rf8X
            5QAOliecH0FKhZm9ipGIGn/KBIun+QFBpaBIzjtAtc/02nXFAyF/GBUc0YfBaA==
            =ECvH
            -----END PGP MESSAGE-----
          fp: 07E36E87C0270E464DB4D663B423D1630A58837C
    unencrypted_suffix: _unencrypted
    version: 3.13.3
