state-passphrase: ENC[AES256_GCM,data:Zj3mjT0GcZQF1pdjDcgNPtQvguE4MfuAqewWQ7YHcOskjNZoRNoXAASLSao=,iv:5T7IDj+83LmWw95BUEL8q/unhSKOD0FPUo6V+50AGc0=,tag:ibxDhVDxR6jF6BLcFg5riQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbElxZnVjV01Zbkw4MmVl
            UXAxQ0w3OUhKVUVVS0Y1NTVWVlcyanMyZ3lVCnRSQVFEWDJGSVVKZDVybW1qbU9w
            d3dNTW0vYWNXUkNxMStjRVEyMmw1MFUKLS0tIDd6eCtSMmFYWXFCdHByTlNjdFlU
            UWFOMFNXdVgrcW5mclp3cDZyZmhMS1kKO4ocLQdZODxHbJe0QO4V5GfmYPtS4bKy
            diqgLeRMklZbkTUEqUACMG5soJ975IAUtcYiC6TJviLVsD521tEkgQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age123w5drucfk50cvw26lt6mrhhnmrdjshg7waqsp4ufnm69ujc04gqhu4h3r
    lastmodified: "2026-10-08T11:44:59Z"
    mac: ENC[AES256_GCM,data:YzRF2FqGfFLYvR94mYQ7POOXdMzmINiWbljYmpgb99x8kDDLnOjQX7dBz3FtPRpz04HBwO6Rq73+V5VSgklqplle8cZDUkkFs/S1qpfWa0dRLouKcdvD8IX99a2llgeL3c3gbKvqD3i/GsV3gCGJr1mtEBXH9Ey1VbHjmXZFGbI=,iv:NVQn9jPB/DxL1aGcLDPAw8sUXZbxkbHEanOZrqNtwyM=,tag:/YmNcPlmVRJoQDPpr8U8aw==,type:str]
    pgp:
        - created_at: "2026-10-07T11:50:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DtCPRYwpYg3wSAQdABNAOe9VTBApbMaRtnARSfxr2kWnaZzohj/8t0HnhYk4w
            PronP7fjBuwjUaoQ8rgRL7wcd76mBr773esUFKnMaNY9EXibun/4WElD+z7TOrTu
            0l4B5DHCHVaTRp8m2xbyVfYShG7WjRnHY/uCrpA3Yi/kfGUawouSKqoxN6hGHk4I
            RTqn65zGac2NpXyV9mkrxfs8oQTm5zEhjZlH3jzfhszG+uIiEZtEIfKR6m3xDp7C
            =x9WE
            -----END PGP MESSAGE-----
          fp: 07E36E87C0270E464DB4D663B423D1630A58837C
    unencrypted_suffix: _unencrypted
    version: 3.13.3
