cloudflare-api-token: ENC[AES256_GCM,data:d3qSFxaQSEnls5bTvTPRLCLbvxSIb1v0m4Q5cidF2UpIg/XTqhR+JjihPq73/w5zl1ksbHc=,iv:ioRyAMSnU7WUQ+8HqCuy4aAtrI+t1jyva3oEf9yzQvM=,tag:3XljuVxHthtIbPqh12u/8w==,type:str]
tailscale-oauth-client-id: ENC[AES256_GCM,data:IgCXla8795+VAqR3AvIn1UA=,iv:ZX4Pv23XBSMu0tYb0YJ1KSn0CZ2ZGEvWC6RhUAk8kMc=,tag:INhY6vFHSdfxFyea/ANChQ==,type:str]
tailscale-oauth-client-secret: ENC[AES256_GCM,data:sImX+NfIrEchQhd5zcMdZU2bpFLPSGbuiL7sbLl3594Vdnva5P2RUlUw+zxoQrfmysKYw0aUnDTVZR8Ss93PMg==,iv:hrMAWaq5+dKopUtndJ/DKYzUgHa7YZgmazUHIuTlzz4=,tag:P92FpgtObB8PZUuMzT0aIA==,type:str]
state-passphrase: ENC[AES256_GCM,data:Zj3mjT0GcZQF1pdjDcgNPtQvguE4MfuAqewWQ7YHcOskjNZoRNoXAASLSao=,iv:5T7IDj+83LmWw95BUEL8q/unhSKOD0FPUo6V+50AGc0=,tag:ibxDhVDxR6jF6BLcFg5riQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbElxZnVjV01Zbkw4MmVl
            UXAxQ0w3OUhKVUVVS0Y1NTVWVlcyanMyZ3lVCnRSQVFEWDJGSVVKZDVybW1qbU9w
            d3dNTW0vYWNXUkNxMStjRVEyMmw1MFUKLS0tIDd6eCtSMmFYWXFCdHByTlNjdFlU
            UWFOMFNXdVgrcW5mclp3cDZyZmhMS1kKO4ocLQdZODxHbJe0QO4V5GfmYPtS4bKy
            diqgLeRMklZbkTUEqUACMG5soJ975IAUtcYiC6TJviLVsD521tEkgQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age123w5drucfk50cvw26lt6mrhhnmrdjshg7waqsp4ufnm69ujc04gqhu4h3r
    lastmodified: "2026-09-29T07:17:42Z"
    mac: ENC[AES256_GCM,data:lrjLtM2hvQuX9bK7W9dVk5kDkKqHQz1ueqy3hvebe9+TfW94jyZdK/CN35w+PftOfj8jz3uFe+el+RcMkR/0dqtFPS61u5o53zbOqsAFtSqdY3xmSgFa2955p6LVkD9tPssYQmPurMb64NcQHz+YLdDrNitAt+8y8DpCcXHCsOg=,iv:UEEt9Xd//CtMIC5d7jBo21Um839Q9oJ+7hKQGZYG7SE=,tag:7+0rHM6slLbGxhEPxzhrJw==,type:str]
    pgp:
        - created_at: "2026-10-07T11:50:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DtCPRYwpYg3wSAQdABNAOe9VTBApbMaRtnARSfxr2kWnaZzohj/8t0HnhYk4w
            PronP7fjBuwjUaoQ8rgRL7wcd76mBr773esUFKnMaNY9EXibun/4WElD+z7TOrTu
            0l4B5DHCHVaTRp8m2xbyVfYShG7WjRnHY/uCrpA3Yi/kfGUawouSKqoxN6hGHk4I
            RTqn65zGac2NpXyV9mkrxfs8oQTm5zEhjZlH3jzfhszG+uIiEZtEIfKR6m3xDp7C
            =x9WE
            -----END PGP MESSAGE-----
          fp: 07E36E87C0270E464DB4D663B423D1630A58837C
    unencrypted_suffix: _unencrypted
    version: 3.13.3
