cloudflare-api-token: ENC[AES256_GCM,data:d3qSFxaQSEnls5bTvTPRLCLbvxSIb1v0m4Q5cidF2UpIg/XTqhR+JjihPq73/w5zl1ksbHc=,iv:ioRyAMSnU7WUQ+8HqCuy4aAtrI+t1jyva3oEf9yzQvM=,tag:3XljuVxHthtIbPqh12u/8w==,type:str]
tailscale-oauth-client-id: ENC[AES256_GCM,data:IgCXla8795+VAqR3AvIn1UA=,iv:ZX4Pv23XBSMu0tYb0YJ1KSn0CZ2ZGEvWC6RhUAk8kMc=,tag:INhY6vFHSdfxFyea/ANChQ==,type:str]
tailscale-oauth-client-secret: ENC[AES256_GCM,data:sImX+NfIrEchQhd5zcMdZU2bpFLPSGbuiL7sbLl3594Vdnva5P2RUlUw+zxoQrfmysKYw0aUnDTVZR8Ss93PMg==,iv:hrMAWaq5+dKopUtndJ/DKYzUgHa7YZgmazUHIuTlzz4=,tag:P92FpgtObB8PZUuMzT0aIA==,type:str]
state-passphrase: ENC[AES256_GCM,data:Zj3mjT0GcZQF1pdjDcgNPtQvguE4MfuAqewWQ7YHcOskjNZoRNoXAASLSao=,iv:5T7IDj+83LmWw95BUEL8q/unhSKOD0FPUo6V+50AGc0=,tag:ibxDhVDxR6jF6BLcFg5riQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZnozUVNMTlFxUktrK3kx
            QzVXN0N3N0RFVkMwa1pzTktDdEdGcU1UWlZNCnNTbkNtNytyWm9JRnFBWFpZRndy
            WG1uVnRtVDJrSVVlVzF2dlV4MDI4NTQKLS0tIDM1Zm5SUGQ0OEVSM1pjUDM1UmhO
            b1RPajJ4WDhLTGpBWHBURWtjVjhWZWsKxlw1iUTFg6Ozvmk9gyr+achjK2O/yZho
            H804xKhY1rxXj3u0g0LSjdBLhvkHJp/zCZ18xaCbiDUpQ+sMtrRR0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kjlpt0mu072vqk8txgkfs7yvehkvk0kysawyqvy96zcqmf49wgkq3hlsag
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMTROWTd1WjdOaUV5Zjdh
            U3FaRVF4VkxkSmpDYXZFb3ZDMEl2VGJzWnpvCnZYdFRDZDJxd2tmRGRBRFNPRXVB
            UlBFaSt1Wk9qTlZkNDU0MlRtSTNaT0kKLS0tIEVrT3Nha1dsV2NWZU1CeHo1RkRS
            K3BDdFZCNWY1Zm5GSE5wbFI0cjExZ0EKuYOdNNJKE+jAW9NX06AYFJXAfVsG+r/c
            43nsWNyyJuzf0wS+wRBnsNhz/iRb+vs4ULREw2FcT1uEqXypnLhmTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age123w5drucfk50cvw26lt6mrhhnmrdjshg7waqsp4ufnm69ujc04gqhu4h3r
    lastmodified: "2026-09-29T07:17:42Z"
    mac: ENC[AES256_GCM,data:lrjLtM2hvQuX9bK7W9dVk5kDkKqHQz1ueqy3hvebe9+TfW94jyZdK/CN35w+PftOfj8jz3uFe+el+RcMkR/0dqtFPS61u5o53zbOqsAFtSqdY3xmSgFa2955p6LVkD9tPssYQmPurMb64NcQHz+YLdDrNitAt+8y8DpCcXHCsOg=,iv:UEEt9Xd//CtMIC5d7jBo21Um839Q9oJ+7hKQGZYG7SE=,tag:7+0rHM6slLbGxhEPxzhrJw==,type:str]
    pgp:
        - created_at: "2026-09-29T07:13:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DtCPRYwpYg3wSAQdAs9ablQCv++6s3Phlz5mtprP/2J4YmmogWYCWYJ1QUw8w
            ciHcmcA5LXR2f9x5JTN4PGD++6nFjTDnI47hLwi3/u8a33Q94dt7Gj07unrkEt3L
            0l4BnGFL5wQ/a6pB3uQ4qNCv+8phRhgVY2UDHQAdcjzITvY/1CFeW1C7lxMKKzS4
            EO1Wgwg33eeYGTYedU4HZS6yueBaPdAg2b37oxkoo7NUZIyCmZsklGUlfAJQaiJo
            =x+3v
            -----END PGP MESSAGE-----
          fp: 07E36E87C0270E464DB4D663B423D1630A58837C
    unencrypted_suffix: _unencrypted
    version: 3.13.3
