[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/var/lib/qbittorrent/.local/share/qBittorrent/logs

[AutoRun]
enabled=true

[BitTorrent]
Session\DefaultSavePath=/data/torrents
Session\DisableAutoTMMByDefault=false
Session\DisableAutoTMMTriggers\CategorySavePathChanged=false
Session\DisableAutoTMMTriggers\DefaultSavePathChanged=false
Session\ExcludedFileNames=
Session\GlobalUPSpeedLimit=200
Session\Port=17348
Session\QueueingSystemEnabled=false
Session\SSL\Port=30088
Session\SubcategoriesEnabled=true
Session\Tags=Best, Comedy, Kids
Session\UseCategoryPathsInManualMode=true

[Core]
AutoDeleteAddedTorrentFile=IfAdded

[Meta]
MigrationVersion=8

[Preferences]
General\Locale=en
MailNotification\req_auth=true
WebUI\AuthSubnetWhitelist=@Invalid()
WebUI\Password_PBKDF2="@ByteArray(xkVo9KYx/eCPQcIvc/JRYg==:ZyXmvUlrDL6ebMsZxdvsCA1d6dmgQSjhAn2RVEx6ZDCVwuG3o/QZ9jE2eL/XwcO4+yDSJBVhrFvp58kwmhVgsA==)"
WebUI\Username=alexander

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
