{
  config,
  lib,
  namespace,
  ...
}:
with lib;
with lib.${namespace};
let
  cfg = config.${namespace}.desktops.aerospace;
  ghosttyCfg = config.${namespace}.cli.terminals.ghostty;
  monitorsCfg = config.${namespace}.desktops.monitors;
  keybindings = import ./keybindings.nix;

  # Derive workspace-to-monitor mapping from desktops.monitors.devices
  monitorsAssignment =
    if monitorsCfg.enable then
      listToAttrs (
        concatMap (m: map (ws: nameValuePair ws m.model) m.workspaces) (
          filter (m: m.enabled && m.workspaces != [ ]) monitorsCfg.devices
        )
      )
    else
      { };

  # Explicit assignment takes precedence, then monitors-derived
  mergedAssignment = monitorsAssignment // cfg.workspaceMonitorAssignment;

  monitorAssignment =
    if mergedAssignment == { } then
      ""
    else
      ''
        [workspace-to-monitor-force-assignment]
      ''
      + concatStringsSep "\n" (
        mapAttrsToList (workspace: monitor: "${workspace} = '${monitor}'") mergedAssignment
      )
      + "\n";
in
{
  options.${namespace}.desktops.aerospace = with types; {
    enable = mkEnableOption "AeroSpace tiling window manager";
    workspaceMonitorAssignment =
      mkOpt (attrsOf str) { }
        "Explicit workspace-to-monitor mapping (overrides monitors-derived values)";
  };

  config = mkIf cfg.enable {
    home.file.".aerospace.toml".text = ''
      # AeroSpace tiling window manager configuration
      # Generated by nix-config — do not edit manually

      start-at-login = true
      enable-normalization-flatten-containers = true
      enable-normalization-opposite-orientation-for-nested-containers = true
      accordion-padding = 30
      default-root-container-layout = 'tiles'
      default-root-container-orientation = 'auto'

      [gaps]
      inner.horizontal = 10
      inner.vertical = 10
      outer.left = 10
      outer.bottom = 10
      outer.top = 10
      outer.right = 10

    ''
    + optionalString ghosttyCfg.enable ''
      # Ghostty uses native macOS tabs which appear as separate windows.
      # Issue: https://github.com/nikitabobko/AeroSpace/issues/68
      # Workaround: https://ghostty.org/docs/help/macos-tiling-wms#aerospace
      [[on-window-detected]]
      if.app-id = 'com.mitchellh.ghostty'
      run = ['layout tiling']

    ''
    + monitorAssignment
    + keybindings;
  };
}
