{
  config,
  lib,
  namespace,
  ...
}:
with lib;
with lib.${namespace};
let
  cfg = config.${namespace}.desktops.aerospace;
  keybindings = import ./keybindings.nix;
  monitorAssignment =
    if cfg.workspaceMonitorAssignment == { } then
      ""
    else
      ''
        [workspace-to-monitor-force-assignment]
      ''
      + concatStringsSep "\n" (
        mapAttrsToList (workspace: monitor: "${workspace} = '${monitor}'") cfg.workspaceMonitorAssignment
      )
      + "\n";
in
{
  options.${namespace}.desktops.aerospace = with types; {
    enable = mkEnableOption "AeroSpace tiling window manager";
    workspaceMonitorAssignment = mkOpt (attrsOf str) { } "Map of workspace name to monitor name (e.g. { \"6\" = \"DELL U2419H\"; })";
  };

  config = mkIf cfg.enable {
    home.file.".aerospace.toml".text = ''
      # AeroSpace tiling window manager configuration
      # Generated by nix-config — do not edit manually

      start-at-login = true
      enable-normalization-flatten-containers = true
      enable-normalization-opposite-orientation-for-nested-containers = true
      accordion-padding = 30
      default-root-container-layout = 'tiles'
      default-root-container-orientation = 'auto'

      [gaps]
      inner.horizontal = 10
      inner.vertical = 10
      outer.left = 10
      outer.bottom = 10
      outer.top = 10
      outer.right = 10

    '' + monitorAssignment + keybindings;
  };
}
