{
  config,
  lib,
  pkgs,
  namespace,
  ...
}:
with lib;
with lib.${namespace};
let
  cfg = config.${namespace}.system.networking.router;

  net = lib.${namespace};
  localDomain = defaults.network.domains.local;

  # ===========================================
  # RouterOS Config Generation (nix-mikrotik style)
  # ===========================================

  # Format a single value for RouterOS
  # Handles: strings, bools, lists, nested attrsets
  formatValue =
    key: value:
    if key == "comment" then
      "comment=\"${value}\""
    else if isBool value then
      "${key}=${if value then "yes" else "no"}"
    else if isList value then
      "${key}=${concatStringsSep "," value}"
    else if isAttrs value then
      concatStringsSep " " (mapAttrsToList formatValue value)
    else
      "${key}=${toString value}";

  # Format a single item (for add commands)
  formatItem = item: concatStringsSep " " (mapAttrsToList formatValue item);

  # Format a section into RouterOS commands
  # - attrset with named keys -> "set <key> <values>" commands
  # - list of attrsets -> "add <values>" commands
  # - attrset with single no_label key -> "set <values>" (no label)
  formatSection =
    path: value:
    if isList value then
      # List -> add commands
      [ path ] ++ map (item: "add ${formatItem item}") value
    else if isAttrs value && value ? no_label then
      # Special no_label -> set without label
      [ path ] ++ [ "set ${formatItem value.no_label}" ]
    else if isAttrs value then
      # Named attrset -> set commands with labels
      [ path ] ++ mapAttrsToList (name: v: "set ${name} ${formatItem v}") value
    else
      [ ];

  # Convert full config to RouterOS script
  toRouterOS =
    sections:
    concatStringsSep "\n" (flatten (mapAttrsToList (path: value: formatSection path value) sections));

  # ===========================================
  # Computed values passed to config.nix
  # ===========================================

  networkAddress = net.networkAddress cfg.gateway;
  prefixLength = net.prefixLength cfg.subnet;

  # ===========================================
  # Full RouterOS Configuration
  # ===========================================

  configArgs = cfg // {
    inherit networkAddress prefixLength localDomain;
  };

  routerConfig = import ./config.nix configArgs;

  # Merge with extra sections from config
  finalConfig = recursiveUpdate routerConfig cfg.extraSections;

  # Generate the .rsc file content
  generatedConfig = ''
    # RouterOS Configuration
    # Generated by nix-config MikroTik module
    # model = RB3011UiAS
    #
    ${toRouterOS finalConfig}
  '';

  # ===========================================
  # Scripts
  # ===========================================

  router-export = pkgs.writeShellScriptBin "router-export" ''
    set -euo pipefail

    ROUTER="${cfg.sshAlias}"
    OUTPUT="''${1:-''${XDG_CONFIG_HOME:-$HOME/.config}/mikrotik/exported.rsc}"

    echo "Exporting configuration from $ROUTER..."
    ssh "$ROUTER" "/export compact" > "$OUTPUT"

    echo "Configuration exported to: $OUTPUT"
    echo "Lines: $(wc -l < "$OUTPUT")"
  '';

  router-import = pkgs.writeShellScriptBin "router-import" ''
    set -euo pipefail

    ROUTER="${cfg.sshAlias}"
    CONFIG="''${XDG_CONFIG_HOME:-$HOME/.config}/mikrotik/config.rsc"
    DRY_RUN=false

    usage() {
      echo "Usage: router-import [OPTIONS]"
      echo ""
      echo "Import Nix-generated RouterOS configuration to MikroTik router"
      echo ""
      echo "Options:"
      echo "  -n, --dry-run  Show config without applying"
      echo "  -h, --help     Show this help"
      exit 0
    }

    while [[ $# -gt 0 ]]; do
      case $1 in
        -n|--dry-run) DRY_RUN=true; shift ;;
        -h|--help) usage ;;
        *) echo "Unknown option: $1"; usage ;;
      esac
    done

    if [[ ! -f "$CONFIG" ]]; then
      echo "Error: Config not found at $CONFIG"
      echo "Run 'home-manager switch' first"
      exit 1
    fi

    # Get WiFi password from SOPS secret
    WIFI_PASSWORD=""
    SECRETS_PATHS=(
      "''${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/secrets/system-network-wifi-password"
      "$HOME/.config/sops-nix/secrets/system-network-wifi-password"
    )

    for path in "''${SECRETS_PATHS[@]}"; do
      if [[ -f "$path" ]]; then
        WIFI_PASSWORD=$(cat "$path")
        break
      fi
    done

    if [[ -z "$WIFI_PASSWORD" ]]; then
      echo "Warning: WiFi password not found in SOPS secrets"
      read -sp "Enter WiFi password (or leave empty): " WIFI_PASSWORD
      echo
    fi

    # Create temp config with password substituted
    TEMP=$(mktemp)
    trap "rm -f $TEMP" EXIT

    if [[ -n "$WIFI_PASSWORD" ]]; then
      WIFI_PASSWORD="$WIFI_PASSWORD" envsubst '$WIFI_PASSWORD' < "$CONFIG" > "$TEMP"
    else
      cp "$CONFIG" "$TEMP"
    fi

    if [[ "$DRY_RUN" == "true" ]]; then
      echo "=== DRY RUN - Config preview ==="
      cat "$TEMP"
      exit 0
    fi

    echo "Creating backup on router..."
    BACKUP_NAME="pre-nix-$(date +%Y%m%d-%H%M%S)"
    ssh "$ROUTER" "/system backup save name=$BACKUP_NAME" || {
      echo "Warning: Backup failed, continuing anyway"
    }

    echo ""
    echo "WARNING: This will import configuration to the router."
    read -p "Continue? [y/N] " -n 1 -r
    echo ""

    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      echo "Aborted."
      exit 0
    fi

    echo "Uploading configuration..."
    scp "$TEMP" "$ROUTER:/nix-config.rsc"

    echo "Importing configuration..."
    ssh "$ROUTER" "/import file-name=nix-config.rsc" || {
      echo "Import failed. Backup available: $BACKUP_NAME"
      exit 1
    }

    # Cleanup
    ssh "$ROUTER" "/file remove nix-config.rsc" 2>/dev/null || true

    echo ""
    echo "Configuration imported successfully!"
    echo "Backup saved as: $BACKUP_NAME"
  '';

  router-diff = pkgs.writeShellScriptBin "router-diff" ''
    set -euo pipefail

    ROUTER="${cfg.sshAlias}"
    CONFIG="''${XDG_CONFIG_HOME:-$HOME/.config}/mikrotik/config.rsc"

    if [[ ! -f "$CONFIG" ]]; then
      echo "Error: Config not found at $CONFIG"
      echo "Run 'home-manager switch' first"
      exit 1
    fi

    TEMP=$(mktemp)
    trap "rm -f $TEMP" EXIT

    echo "Fetching current configuration from $ROUTER..."
    ssh "$ROUTER" "/export compact" > "$TEMP"

    echo ""
    echo "=== DIFF (local Nix config vs router) ==="
    echo "< = Nix generated"
    echo "> = Current router"
    echo ""

    # Normalize for comparison: remove timestamps, sort
    diff --color=auto -u \
      <(grep -v "^# " "$CONFIG" | grep -v "^\$WIFI_PASSWORD" | sort) \
      <(grep -v "^# " "$TEMP" | sort) || true
  '';

  # ===========================================
  # Option Types
  # ===========================================

  hostEntryType = types.submodule {
    options = {
      ip = mkStringOpt "" "IP address";
      mac = mkStringOpt "" "MAC address";
      comment = mkStringOpt "" "Description (optional, defaults to hostname)";
      dns = mkBoolOpt true "Create DNS A record for this host";
      aliases = mkOpt (types.listOf types.str) [ ] "Additional DNS aliases (short names)";
    };
  };

in
{
  options.${namespace}.system.networking.router = with types; {
    enable = mkBoolOpt false "Enable MikroTik router configuration management";

    # Connection settings
    sshAlias = mkStringOpt "router" "SSH config alias";

    # Network settings
    subnet = mkStringOpt defaults.network.subnet "Network subnet (CIDR)";
    gateway = mkStringOpt defaults.network.gateway "Gateway IP";
    dhcpRange = mkStringOpt defaults.network.dhcpRange "DHCP pool range";

    # WiFi
    wifi = {
      ssid = mkStringOpt defaults.network.wifi.ssid "WiFi SSID";
    };

    # DNS
    dns = {
      upstream = mkOpt (listOf str) defaults.network.dns.upstream "Upstream DNS servers";
    };

    # Hardware settings
    bridge = {
      adminMac = mkStringOpt "08:55:31:E9:21:73" "Bridge admin MAC address";
    };

    lte = {
      apn = mkStringOpt "ks" "LTE APN";
      name = mkStringOpt "Kyivstar" "LTE provider name";
    };

    ovpn = {
      macAddress = mkStringOpt "FE:24:A6:AA:80:85" "OpenVPN server MAC address";
    };

    # System
    timezone = mkStringOpt defaults.locale.timeZone "Router timezone";

    # Network hosts - single source of truth for DHCP leases and DNS records
    hosts = mkOpt (attrsOf hostEntryType) { } "Network hosts - generates DHCP leases and DNS records";

    # Firewall address lists
    firewallAddressLists = mkOpt (attrsOf (
      listOf str
    )) { } "Firewall address lists (e.g. { TV = [ \"10.0.0.50/32\" \"10.0.0.51/32\" ]; })";

    # Extra RouterOS sections (for customization)
    extraSections = mkOpt attrs { } "Additional RouterOS sections to merge into config";

    # Derived/computed values (readonly)
    dhcpLeases = mkOption {
      type = listOf attrs;
      readOnly = true;
      description = "DHCP leases generated from hosts";
    };

    dnsStaticRecords = mkOption {
      type = listOf attrs;
      readOnly = true;
      description = "DNS static records generated from hosts";
    };
  };

  config = mkIf cfg.enable {
    # Initialize derived/computed values
    ${namespace}.system.networking.router = {
      dhcpLeases = mapAttrsToList (name: host: {
        address = host.ip;
        mac-address = toUpper host.mac;
        comment = if host.comment != "" then host.comment else name;
        server = "defconf";
      }) cfg.hosts;

      dnsStaticRecords =
        let
          # Primary records
          primaryRecords = flatten (
            mapAttrsToList (
              name: host:
              optional host.dns {
                address = host.ip;
                name = net.hosts.local name;
                type = "A";
              }
            ) cfg.hosts
          );
          # Alias records
          aliasRecords = flatten (
            mapAttrsToList (
              name: host:
              map (alias: {
                address = host.ip;
                name = net.hosts.local alias;
                type = "A";
              }) host.aliases
            ) cfg.hosts
          );
        in
        primaryRecords ++ aliasRecords;
    };

    # Install management scripts
    home.packages = [
      router-export
      router-import
      router-diff
    ];

    # Generate configuration file
    xdg.configFile."mikrotik/config.rsc".text = generatedConfig;
  };
}
