# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  pkgs,
  namespace,
  ...
}:
with lib;
with lib.${namespace};
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  ${namespace} = {
    hardware = {
      audio.enable = true;
      bluetooth.enable = true;
      zsa.enable = true;
      video.nvidia.enable = true;
    };
  };

  boot = {
    initrd = {
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usb_storage"
        "usbhid"
        "sd_mod"
      ];
      kernelModules = [ ];
    };

  };

  hardware = {
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };

}
