# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usb_storage"
        "usbhid"
        "sd_mod"
      ];
      kernelModules = [ "kvm-intel" ];
    };
  };

  # Enable NVIDIA drivers
  services.xserver.videoDrivers = [ "nvidia" ];

  hardware = {
    nvidia = {
      # Modesetting is required for Wayland
      modesetting.enable = true;

      # Enable power management (will impact performance but better battery life)
      powerManagement.enable = true;

      # Enable the proprietary NVIDIA drivers (legacy 390 version)
      package = config.boot.kernelPackages.nvidiaPackages.legacy_390;

      # Enable DRM kernel mode setting
      open = true;

      # Prime configuration for laptops with hybrid graphics
      prime = {
        offload.enable = false; # Set to true if you want to use NVIDIA Prime render offloading
        # If you have a laptop with hybrid graphics, uncomment and adjust these:
        # intelBusId = "PCI:0:2:0";
        # nvidiaBusId = "PCI:1:0:0";
      };
    };

    # Enable OpenGL
    opengl = {
      enable = true;
    };

    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
