tailscale-oauth-client-id: ENC[AES256_GCM,data:SrbqyjWfcu0vevV1nwFkfdM=,iv:zymMJ4N2qT7sXp9qss7NmKNeEkBQjrsxvSuXYkns5jg=,tag:mmh6HqKXqZrKBrMUaHqtRA==,type:str]
tailscale-oauth-client-secret: ENC[AES256_GCM,data:imYZInuv73CsDolTimozS6uSNbM6pjnYay/RQ2ag95wdEzKUPdleHlrDZvWjLrRsCECGh9unthI1+wp+ZDsxaQ==,iv:gvleLVpdDMr3J1hDvxEwOpsBca/0U4MPSsGN0gQ5W+4=,tag:oEzRz+VTS/1pAcIwAqPdGA==,type:str]
state-passphrase: ENC[AES256_GCM,data:qLz0skpeSkgB9b+WnfjEYsjBud4AVXu6IMiYJYxsnTQbcWFjyk5o71YkOlQ=,iv:JbHrv2y/ZYpuxThAoOhYr7Glj4yVzWlodXpNJDLLnKY=,tag:aA3xXo/ZbVkpFuPRzETSJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZ0ZDWnZKRmZPMFRlYnYw
            S0o3b1kwNE1tY2J3VkNDR1ZNbjdyOC82SkRVCjhYZWdMRVMyeTA4RUkvYWEwRWJa
            YUVJT0ZCZTllVkRMRGQ5Sk5nMzVhYUUKLS0tIEZSbkVmYnErMEo1aHlCUWoyWDVX
            UVZlLzczVzBNTVNmUDhSMHdXOUgzSWcKpscDpDyGoZPswhz5NKAzqPy5SV+wt966
            ruXlDHal5OcfILLszT7/VLv6dbvmRcKe8VSA50vIuDA18uwtE3OxeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kjlpt0mu072vqk8txgkfs7yvehkvk0kysawyqvy96zcqmf49wgkq3hlsag
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYkYrS3k2NTFBVnExSWVp
            RnN6VlJJMi92eVZFSU9ONS81WjFYWlNURFhJClJ2ejVGdHNwR1Fib2FYamxPZWx0
            bDZzdDBJM0JRRXVnUlNsOUZtRVpUVnMKLS0tIHVkZnhobXZLd2I5cTJDVFlPdXFn
            V2lkQkx3b25KeUw3Y0JpUTRJcENVd0EKPM1Wu+amUDok9cJ3dRi1wyzHT6fszufD
            2Yg63uj+tHHToXHZG2zpuPhtL8591piZ2LnJqUnKrSlPdj3B0A9Xsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age123w5drucfk50cvw26lt6mrhhnmrdjshg7waqsp4ufnm69ujc04gqhu4h3r
    lastmodified: "2026-09-28T12:11:38Z"
    mac: ENC[AES256_GCM,data:43DjSOSD4K/6He+rjoXQ1tEC8m7c9vKCIm/i8cD/naUIx+8BEuizyn9j9jFCm3QGA3sstCi62CP1lfmg2PF2/bwetcAkjx8gcfkPbrOjvwCbU+g3zbZ9M+yYQI3ij//ZmF1GiXSwRXx0kA/YqEZf1cbEacqnu5HWfVJggzUR+8Y=,iv:G0L5FUVBB554QbEot13uJ29yhpygCopGTmP7KxkoqVQ=,tag:p0GmlNIU3BT6Y1oh1UomuA==,type:str]
    pgp:
        - created_at: "2026-09-28T12:04:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DtCPRYwpYg3wSAQdAo/mXxpjWZmrwZi8gLYaoLAIBo0gWLjpguwrA8zM0/0Iw
            YG1qAJw9lGYb7nJiwwHaWFDJy1QpdmK6y9R9wBKomFmB2BAmhv2k0mJwJtjO7d+V
            0l4BMHkcmRwF2Hfh9vKDUsBctoaz0vSzkw9kgVWgw6/7JLDHvG8u86yMnR9iOoD2
            /fHIAA/7wnltPA578+6zsMeA9whM18ekUcmefiHdrHAO8Ezeoot2XNdXUMdsLyIb
            =Vqyf
            -----END PGP MESSAGE-----
          fp: 07E36E87C0270E464DB4D663B423D1630A58837C
    unencrypted_suffix: _unencrypted
    version: 3.13.3
