tailscale-oauth-client-id: ENC[AES256_GCM,data:SrbqyjWfcu0vevV1nwFkfdM=,iv:zymMJ4N2qT7sXp9qss7NmKNeEkBQjrsxvSuXYkns5jg=,tag:mmh6HqKXqZrKBrMUaHqtRA==,type:str]
tailscale-oauth-client-secret: ENC[AES256_GCM,data:imYZInuv73CsDolTimozS6uSNbM6pjnYay/RQ2ag95wdEzKUPdleHlrDZvWjLrRsCECGh9unthI1+wp+ZDsxaQ==,iv:gvleLVpdDMr3J1hDvxEwOpsBca/0U4MPSsGN0gQ5W+4=,tag:oEzRz+VTS/1pAcIwAqPdGA==,type:str]
state-passphrase: ENC[AES256_GCM,data:qLz0skpeSkgB9b+WnfjEYsjBud4AVXu6IMiYJYxsnTQbcWFjyk5o71YkOlQ=,iv:JbHrv2y/ZYpuxThAoOhYr7Glj4yVzWlodXpNJDLLnKY=,tag:aA3xXo/ZbVkpFuPRzETSJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOTRkVWFZb1JaMG02a29n
            UTNSL2NlQ2ppamcvbmg5Yks0WFJ3dDNMcHcwClZyU3NINjN6ZFpNQUdTdVlnMGEx
            RUk0RnFWWVl4ZVhlS3JEOVBEMkFYZmsKLS0tIFY3WE5xRFhJcERlZCtWcUFMaHlj
            RzAydGhYMjREWWRGeGZzWkdtRzl0WG8Kw/06+nGnl4pAhCBC0KW7YTwMOBHzOSDU
            Xk0++Be/XxUZ/UKdYhJPrcARBQRBAzsd2ozVG0fQY2/cRVUnoD8YxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age123w5drucfk50cvw26lt6mrhhnmrdjshg7waqsp4ufnm69ujc04gqhu4h3r
    lastmodified: "2026-09-28T12:11:38Z"
    mac: ENC[AES256_GCM,data:43DjSOSD4K/6He+rjoXQ1tEC8m7c9vKCIm/i8cD/naUIx+8BEuizyn9j9jFCm3QGA3sstCi62CP1lfmg2PF2/bwetcAkjx8gcfkPbrOjvwCbU+g3zbZ9M+yYQI3ij//ZmF1GiXSwRXx0kA/YqEZf1cbEacqnu5HWfVJggzUR+8Y=,iv:G0L5FUVBB554QbEot13uJ29yhpygCopGTmP7KxkoqVQ=,tag:p0GmlNIU3BT6Y1oh1UomuA==,type:str]
    pgp:
        - created_at: "2026-10-07T11:50:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DtCPRYwpYg3wSAQdAYmjjkXXic4XHkqYIH3bohy/luuw5lKNOiKjM5Z2pFl4w
            oNyKowYivkkT+kktuqiLJJ69NbTS8tz2ZjQIjDTtUbbiX/ps//4uevU1FKPl0Ira
            0l4Biop7QfswFdMLBU4taieX9/ksTFbRVhxGrdXlp5nj74CfMWe8gXDhVfCqVM96
            TekOninY1uU0lQTh7dgBKeXSfkjIZcYdPX3IqmmjgIQPBB5BwyBLxj91TYbdXB1b
            =qLxU
            -----END PGP MESSAGE-----
          fp: 07E36E87C0270E464DB4D663B423D1630A58837C
    unencrypted_suffix: _unencrypted
    version: 3.13.3
