router-api-password: ENC[AES256_GCM,data:3NvqbB09iwKI,iv:EJdd/Qm/Z0lRODX0k3zBNp7refHIlN5fpXJYABirOJU=,tag:EcL6fOhIxv3POsYY9rqsEg==,type:str]
state-passphrase: ENC[AES256_GCM,data:+46dS3k32pVa0d75Y9aDgxR2jThcrfFebQi0X0PVisPLous0NlyN7KxPgYU=,iv:3ybiE8hiXV7K5Hgo+OKbjduF46OfOxY7B9AfevPJN4c=,tag:RJMSzKG5Y1VMFzcIjIP7wA==,type:str]
wifi-password: ENC[AES256_GCM,data:JHyGDUYzrjg=,iv:2Fp5sLodsUZEuKsd4Z7ldSeYHt9JTK4OFRPWl7lT5s0=,tag:+DXHUz6rdfJjpKFVaKyEpQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNTZxbzc1bWJnMUVHa2RL
            SUJzU3k0Z3B4SmtFQnFNR1NRMWUrNUpSSDJvCnBPNnlDMC9YcktQYWxtMmFjd1VS
            VFcxbmJ1NUdIRndJTEpCd05nM1hmZWsKLS0tIG1sdVJoeHFmWER0bXlLV05jSlVt
            VUd0d2FRQ09xZUJGRGtOUmd0RWZ2TDgK1Ee/A+vwSTErudD2ER7bz0C48lsvbhaO
            9fq0D/ZhIbsiRmQmYrkk6BcQL7VsbQjNS1ZqvSCO0KHIN7rN6PbKYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age123w5drucfk50cvw26lt6mrhhnmrdjshg7waqsp4ufnm69ujc04gqhu4h3r
    lastmodified: "2026-02-24T17:00:33Z"
    mac: ENC[AES256_GCM,data:jNxT7nEgMlDt19M1ij+CWfjxATpa80cN2zItv3AUhlKbGc+N4QzqnkxnWTD5iu+sPzBZBzakr3SwAC4tu+awKXmcDMbyOmHkhmlWW6kKEE6EVkErpQu/r414dN822zvLfSGkkEHP+joRwSdM1fR8k7aF+ovt0QC3MudfN6Qzyiw=,iv:eoQ8wlHhrY0RnnHN0ueN3cF691PhLXWAjuE1SxrQgKc=,tag:qcdeFzvY0sau0sWoJOfkoA==,type:str]
    pgp:
        - created_at: "2026-10-07T11:50:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DtCPRYwpYg3wSAQdA7mg0Quvce6Wq+ncb4RGZW7Oq49bBd5M3HO0mgWryYGcw
            PuE/KppHy9enjC5d1O2zVnIFmhxPhOOo29rgQW7IaIccwDXDlc1nYsNP2z7b9elz
            0l4BD5jJiDBmgk6rxmv3OHIJ0qlc5/w/jUmuuJdLJ9UvQjJninahdJuHGfe0BeWR
            OOfJ9F8iDOEn1We4BmT2pQpTDSxWqUIVvZ7mb5Yd7kPDw3CYCHlIq0lPvZP6W7Qu
            =Dwvp
            -----END PGP MESSAGE-----
          fp: 07E36E87C0270E464DB4D663B423D1630A58837C
    unencrypted_suffix: _unencrypted
    version: 3.11.0
