{
  pkgs,
  lib,
  config,  
  username,
  ...
}: let 
  username = config.users.users.alexander.name;
in {


  environment.systemPackages = with pkgs; [
    greetd.tuigreet
  ];
  
  services.greetd = {
    enable = true;
    vt = 3;
    settings = {
      default_session = {
        # Wayland Desktop Manager is installed only for user via home-manager!
        user = username;
        # .wayland-session is a script generated by home-manager, which links to the current wayland compositor(sway/hyprland or others).
        # with such a vendor-no-locking script, we can switch to another wayland compositor without modifying greetd's config here.
        # command = "$HOME/.wayland-session"; # start a wayland session directly without a login manager
        command = "${pkgs.greetd.tuigreet}/bin/tuigreet --time --cmd Hyprland"; # start Hyprland with a TUI login manager
      };
    };

  };
}
